# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from operations_research import linear_solver_pb2 as operations__research_dot_linear__solver__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in operations_research/linprog_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LinProgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MILPModel = channel.unary_unary(
                '/operations_research.LinProgService/MILPModel',
                request_serializer=operations__research_dot_linear__solver__pb2.MPModelRequest.SerializeToString,
                response_deserializer=operations__research_dot_linear__solver__pb2.MPSolutionResponse.FromString,
                _registered_method=True)


class LinProgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MILPModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LinProgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MILPModel': grpc.unary_unary_rpc_method_handler(
                    servicer.MILPModel,
                    request_deserializer=operations__research_dot_linear__solver__pb2.MPModelRequest.FromString,
                    response_serializer=operations__research_dot_linear__solver__pb2.MPSolutionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operations_research.LinProgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('operations_research.LinProgService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LinProgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MILPModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operations_research.LinProgService/MILPModel',
            operations__research_dot_linear__solver__pb2.MPModelRequest.SerializeToString,
            operations__research_dot_linear__solver__pb2.MPSolutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
