# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operations_research/linprog_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from operations_research import linear_solver_pb2 as operations__research_dot_linear__solver__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)operations_research/linprog_service.proto\x12\x13operations_research\x1a\'operations_research/linear_solver.proto2m\n\x0eLinProgService\x12[\n\tMILPModel\x12#.operations_research.MPModelRequest\x1a\'.operations_research.MPSolutionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operations_research.linprog_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINPROGSERVICE']._serialized_start=107
  _globals['_LINPROGSERVICE']._serialized_end=216
# @@protoc_insertion_point(module_scope)
